version: '3.7.11'
services:
  recognizer:
    image: recognizer-image
    volumes:
      - .:/container
    working_dir: /container
    command: streamlit run streamlit.py
    ports:
      - "8502:8501"
